### ISSUE TITLE
無駄な空白行を削除するようにする

### ISSUE THREAD

**Issue by kiotex** [KosukeMizuno/esapy#27]
`</summary>`の後と、`</details>`の前の無駄な空白行が追加されてしまうのが気になる。

例↓
```html
<details open>
<summary>[32]: code source</summary>


` ` `python
import numpy as np

def calc_theta(MFD, f):
    return MFD/f * 180/np.pi

# For test
print(f"test: {calc_theta(3.5e-6, 4.0e-3)} deg")
` ` `


</details>
```

**Comment by KosukeMizuno** [comment]
htmlタグとmarkdown記法の間には少なくとも一行以上の空行が必要なので、とりあえず色んな所で入れています。
１行じゃなく２行になっているのは判定するのが面倒だから。
Markdownでは何行あいても同じなので無視している。

esa側で修正しても再アップすると消えるので、生成されるmarkdownの見た目にはこだわらないほうがいいね
それかコメントにesaで書き換えるなと書いたほうがいいかもしれないな

**Comment by KosukeMizuno** [comment]
↑のコメントに対応する修正をした

無駄な空白は対処してない
